set nocompatible
set ai ar sm rnu
set t_Co=256
set nu
set ai
set tabstop=4
set shiftwidth=4
set softtabstop=4
colorscheme torte
syntax on
filetype plugin indent on
se makeprg=g++\ %\ -Wall\ -Wshadow\ -std=c++14\ -o\ %<.out
map <F9> :make <CR>:!./%<.out<CR>
