set nocompatible
set ai ar sm nu
set t_Co=256
set nu
set ai
set tabstop=4
set shiftwidth=4
set softtabstop=4
colorscheme darkblue
syntax on
filetype plugin indent on
se makeprg=g++\ %\ -Wall\ -Wshadow\ -std=c++14\ -o\ %<.out
map <F9> :w <CR> :make <CR>:!./%<.out<CR>
map <F10> :w <CR> :make <CR>:!./%<.out < %<.in<CR>
map <F3> :w gg=G
